Rework _check_networkconfig and drop FORCE_NIC comma support
Rework _check_networkconfig to allow for the case were a
interface my not yet have reached an operating state and/or have
an IP address allocated. This is required during a resume from
suspend or hibernating where systemd no longer honer the
network-online.target as this is only valid from a clean boot.

The rework allows the configuration of a retry loop allowing
modification of the number of retry allowed (NET_IFACE_RETRY) and
time to sleep between retry (NET_IFACE_SLEEP).

This change has also show problems with FORCE_NIC. Firstly a comma
is allowed in a network interface name and hence we cannot use a
command delimited list. However, spaces are not allowed in the
interface name so we can use a space delimited list. Secondly
_check_config did validate the details of FORCE_NIC and hence a
invalid name could have been applied. Thirdly if a list of network
interfaces was supplied in FORCE_NIC the regular expression used a
filer was to loose and could allows the incorrect by
_check_networkconfig to selection an invalid interfaces i.e. the
lo could be selected incorrectly.

diff --git a/usr/sbin/autoshutdown b/usr/sbin/autoshutdown
--- a/usr/sbin/autoshutdown
+++ b/usr/sbin/autoshutdown
@@ -897,6 +897,38 @@ _check_config() {
         _log "ERR: Exiting ..."
         exit 140; }
 
+    [[ -z "${FORCE_NIC:-}" ||
+        "${FORCE_NIC}" =~ ^([^ /]{1,15})([ ][^ /]{1,15})*$ ]] || {
+        _log "WARNING: FORCE_NIC not set properly: ${FORCE_NIC}"
+        _log "WARNING: FORCE_NIC must be in a space delimited list"
+        _log "ERR: Exiting ..."
+        exit 140; }
+
+    [ -z "${FORCE_NIC:-}" ] &&
+        FORCE_NIC="${DEFAULT_FORCE_NIC}"
+
+    # NET_IFACE_RETRY (1 - 100).
+    [[ -z "${NET_IFACE_RETRY:-}" ||
+       "${NET_IFACE_RETRY}" =~ ^([1-9][0-9]|100)$ ]] || {
+        _log "WARNING: NET_IFACE_RETRY not set properly: ${NET_IFACE_RETRY}"
+        _log "WARNING: NET_IFACE_RETRY must be in the range: '1' - '100'"
+        _log "WARNING: NET_IFACE_RETRY set to default: ${DEFAULT_NET_IFACE_RETRY}"
+        NET_IFACE_RETRY="${DEFAULT_NET_IFACE_RETRY}"; }
+
+    [ -z "${NET_IFACE_RETRY:-}" ] &&
+        NET_IFACE_RETRY="${DEFAULT_NET_IFACE_RETRY}"
+
+    # NET_IFACE_SLEEP (1 - 60 seconds).
+    [[ -z "${NET_IFACE_SLEEP:-}" ||
+       "${NET_IFACE_SLEEP}" =~ ^([1-5][0-9]*|60)$ ]] || {
+        _log "WARNING: NET_IFACE_SLEEP not set properly: ${NET_IFACE_SLEEP}"
+        _log "WARNING: NET_IFACE_SLEEP must be in the range: '1' - '60' seconds"
+        _log "WARNING: NET_IFACE_RETRY set to default: ${DEFAULT_NET_IFACE_SLEEP}"
+        NET_IFACE_SLEEP="${DEFAULT_NET_IFACE_SLEEP}"; }
+
+    [ -z "${NET_IFACE_SLEEP:-}" ] &&
+        NET_IFACE_SLEEP="${DEFAULT_NET_IFACE_SLEEP}"
+
     # CYCLES (1 - 999).
     [[ "${CYCLES}" =~ ^([1-9]|[1-9][0-9]|[1-9][0-9]{2})$ ]] || {
         _log "WARNING: CYCLES not set properly: ${CYCLES}"
@@ -1114,9 +1146,9 @@ _check_config() {
 #
 #   Name       : _check_networkconfig
 #   Parameters : None
-#   Globals    : $FORCE_NIC : Force network interface lookup make sure you
-#                             insert a comma or space between each network
-#                             interface to be checked.
+#   Globals    : $FORCE_NIC : Force network interface lookup using a space
+#                             delimited list of network interface or partial
+#                             interface names to be checked.
 #              : $NIC_TO_IP : Associative array for storing network interface
 #                             to IP address mappings.
 #   Return     : 0 on success.
@@ -1125,27 +1157,33 @@ _check_networkconfig() {
     _log "INFO: ------------------------------------------------------"
     _log "INFO: Find available network interfaces and their IPv4 addresses"
 
-    local -r net_ifaces="${FORCE_NIC:-"en,eth,wlan,bond,br,usb"}"
-    local net_iface ip; while read -r net_iface ip; do
-        local state; state="$(< "/sys/class/net/${net_iface}/operstate")"
-        local ipv4_valid="true"
-        [[ "${ip}" =~ ^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$ ]] ||
-            ipv4_valid="false"
+    local net_iface; while read -r net_iface; do
+        for (( n=0; n < NET_IFACE_RETRY; n++ )); do
+            local state; state="$(< "/sys/class/net/${net_iface}/operstate")"
+            local ip; ip="$(LC_ALL=C ip -br -4 addr show dev "${net_iface}" |
+                            awk '{sub(/\/[0-9]+/,"",$3); print $3}')"
+            local ipv4_valid="true"
+            [[ "${ip}" =~ ^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$ ]] ||
+                ipv4_valid="false"
 
-        [ "${DEBUG}" == "true" ] && {
-            _log "DEBUG: Network interfaces: ${net_iface}"
-            _log "DEBUG: Network interfaces status: ${state}"
-            _log "DEBUG: Network interfaces IPv4 address: ${ip}"
-            _log "DEBUG: Network interfaces address valid: ${ipv4_valid}"; }
+            [ "${DEBUG}" == "true" ] && {
+                _log "DEBUG: Network interfaces: ${net_iface}"
+                _log "DEBUG: Network interfaces status: ${state}"
+                _log "DEBUG: Network interfaces IPv4 address: ${ip:-N/A}"
+                _log "DEBUG: Network interfaces address valid: ${ipv4_valid}"; }
 
-        [[ "${ipv4_valid}" == "true" &&
-           "${state}" =~ ^(unknown|dormant|up)$ ]] && {
-            _log "INFO: '${net_iface}' has IPv4 address: ${ip}"
-            NIC_TO_IP["${net_iface}"]="${ip}"; }
+            [[ "${ipv4_valid}" == "true" &&
+                "${state}" =~ ^(unknown|dormant|up)$ ]] && {
+                _log "INFO: '${net_iface}' has IPv4 address: ${ip}"
+                NIC_TO_IP["${net_iface}"]="${ip}"
+                break; }
 
-    done < <(LC_ALL=C ip -o -4 address show |
-                awk -F"/| " -v regex=": ${net_ifaces//[, ]/|: }" \
-                    '$0 ~ regex {print $2 " " $7}')
+            _log "INFO: '${net_iface}' status: ${state}, IPv4 address: ${ip:-N/A}, retrying in ${NET_IFACE_SLEEP}s ..."
+            sleep "${NET_IFACE_SLEEP}"
+        done
+    done < <(LC_ALL=C ip -br link show |
+                awk -v regex="^(${FORCE_NIC// /|})" \
+                    '$1 ~ regex && !/SLAVE/ {print $1}')
 
     [ -z "${!NIC_TO_IP[*]}" ] && {
         _log "ERR: No valid network interface found, exiting ..."
@@ -1269,11 +1307,10 @@ _check_config
     _log "INFO: Script disabled, exiting here ..."
     exit 0; }
 
-_check_networkconfig
-
 [ "${DEBUG}" == "true" ] && {
     _log "DEBUG: -----------------------------------------------------"
     for var in "FAKE:N/A" "VERBOSE:N/A" "CYCLES:N/A" "SLEEP:N/A" \
+               "FORCE_NIC:N/A" "NET_IFACE_RETRY:N/A" "NET_IFACE_SLEEP:N/A" \
                "SHUTDOWNCOMMAND:N/A" "CHECKCLOCKACTIVE:N/A" "UPHOURS:N/A" \
                "OVERRIDEUPHOURS:N/A" "IPCHECK:N/A" "RANGE:N/A" \
                "CHECKSOCKETS:N/A" "NSOCKETNUMBERS:N/A" \
@@ -1289,6 +1326,8 @@ _check_networkconfig
     for _plugin in /etc/autoshutdown.d/*; do
         [ ! -f "${_plugin}" ] || _log "DEBUG: Plugin: ${_plugin}"
     done; }
+
+_check_networkconfig
 
 _log "INFO: --------------- Initialise states --------------------"
 
